#!/usr/bin/env python3
"""
Unified post-processing script for WormMine

Removes problematic records from the database based on removal lists
generated by generate_removal_lists.py

Usage:
    python post_process.py <database> [--input-dir <dir>] [--dry-run]

Example:
    python post_process.py wormmine_final --input-dir ./removal_lists
    python post_process.py wormmine_final --dry-run
    python post_process.py wormmine_final --backup  # dumps db before processing
"""

import sys
import os
import argparse
import logging
import subprocess
from pathlib import Path
from datetime import datetime

from sqlalchemy import create_engine, text

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Model to table mapping
MODELS = {
    'gene': 'gene',
    'protein': 'protein',
    'cds': 'cds',
    'transcript': 'transcript',
    'mrna': 'mrna',
    'anatomyterm': 'anatomyterm',
    'allele': 'allele',
    'exon': 'exon',
    'organism': 'organism',
}


DEFAULT_HOST = 'intermine-postgres.cmnnhlso7wdi.us-east-1.rds.amazonaws.com'
DEFAULT_CREDS = 'postgres:zpS-4BNKUAOiulFtIUOZE2kvDlWi9mKmuak8Zs9LJz0'


def get_credentials(creds_file=None):
    """Get database credentials"""
    if creds_file:
        return Path(creds_file).read_text().strip()

    # Try to find pgcreds file
    for path in ['./pgcreds', '../pgcreds', '~/.pgcreds']:
        p = Path(path).expanduser()
        if p.exists():
            return p.read_text().strip()

    # Use default credentials
    return DEFAULT_CREDS


def backup_database(database, host, creds, backup_dir='./backups'):
    """Dump database before processing"""
    backup_dir = Path(backup_dir)
    backup_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    backup_file = backup_dir / f"{database}_{timestamp}.sql.gz"

    user, password = creds.split(':')

    logger.info(f"Backing up {database} to {backup_file}...")

    env = {'PGPASSWORD': password}
    cmd = [
        'pg_dump',
        '-h', host,
        '-U', user,
        '-d', database,
        '-Fc',  # custom format (compressed)
    ]

    try:
        with open(backup_file.with_suffix(''), 'wb') as f:
            result = subprocess.run(cmd, stdout=f, stderr=subprocess.PIPE, env={**os.environ, **env})

        if result.returncode != 0:
            logger.error(f"Backup failed: {result.stderr.decode()}")
            sys.exit(1)

        # Compress if not using custom format
        logger.info(f"Backup complete: {backup_file.with_suffix('')}")
        return backup_file.with_suffix('')

    except FileNotFoundError:
        logger.error("pg_dump not found. Install PostgreSQL client tools.")
        sys.exit(1)


def get_connection(database, host='localhost', creds_file=None):
    """Create database connection"""
    creds = get_credentials(creds_file)

    db_string = f"postgresql://{creds}@{host}/{database}"
    logger.info(f"Connecting to {host}/{database}")

    engine = create_engine(db_string, isolation_level='AUTOCOMMIT')
    return engine.connect(), creds


def clean_anatomy_cdata(connection, identifiers, dry_run=False):
    """Clean CDATA from anatomyterm definition field (UPDATE, not DELETE)"""
    if not identifiers:
        return 0

    total = len(identifiers)
    updated = 0

    if dry_run:
        logger.info(f"[DRY-RUN] Would clean CDATA from {total} anatomyterm records")
        return total

    for identifier in identifiers:
        try:
            # Get current definition
            result = connection.execute(text(
                f"SELECT definition FROM anatomyterm WHERE primaryidentifier = '{identifier}'"
            ))
            row = result.fetchone()
            if row and row[0]:
                definition = row[0]
                new_definition = definition.replace("<![CDATA[", "").replace("]]>", "").replace("'", "`")
                connection.execute(text(
                    f"UPDATE anatomyterm SET definition = '{new_definition}' WHERE primaryidentifier = '{identifier}'"
                ))
                updated += 1
                logger.debug(f"Cleaned CDATA from {identifier}")
        except Exception as e:
            logger.error(f"Error cleaning {identifier}: {e}")

    return updated


def clean_rnai_cdata(connection, dry_run=False):
    """Clean CDATA from RNAi remark, secondaryidentifier, phenotyperemark fields"""
    updated = 0

    if dry_run:
        logger.info("[DRY-RUN] Would clean CDATA from RNAi records")
        return 0

    # Clean remark field
    logger.info("Cleaning CDATA from RNAi remark field...")
    result = connection.execute(text("SELECT primaryidentifier, remark FROM rnai WHERE remark LIKE '%CDATA%'"))
    for row in result:
        rnai_id, remark = row[0], row[1]
        if remark:
            new_remark = remark.replace("<![CDATA[", "").replace("]]>", "").replace("'", "`")
            try:
                connection.execute(text(
                    f"UPDATE rnai SET remark = '{new_remark}' WHERE primaryidentifier = '{rnai_id}'"
                ))
                updated += 1
            except Exception as e:
                logger.error(f"Error updating remark for {rnai_id}: {e}")

    # Clean secondaryidentifier field
    logger.info("Cleaning CDATA from RNAi secondaryidentifier field...")
    result = connection.execute(text("SELECT primaryidentifier, secondaryidentifier FROM rnai WHERE secondaryidentifier LIKE '%CDATA%'"))
    for row in result:
        rnai_id, sec_id = row[0], row[1]
        if sec_id:
            new_sec_id = sec_id.replace("<![CDATA[", "").replace("]]>", "").replace("'", "`")
            try:
                connection.execute(text(
                    f"UPDATE rnai SET secondaryidentifier = '{new_sec_id}' WHERE primaryidentifier = '{rnai_id}'"
                ))
                updated += 1
            except Exception as e:
                logger.error(f"Error updating secondaryidentifier for {rnai_id}: {e}")

    # Clean phenotyperemark field
    logger.info("Cleaning CDATA from RNAi phenotyperemark field...")
    result = connection.execute(text("SELECT primaryidentifier, phenotyperemark FROM rnai WHERE phenotyperemark LIKE '%CDATA%'"))
    for row in result:
        rnai_id, phenotype = row[0], row[1]
        if phenotype:
            new_phenotype = phenotype.replace("<![CDATA[", "").replace("]]>", "").replace("'", "`")
            try:
                connection.execute(text(
                    f"UPDATE rnai SET phenotyperemark = '{new_phenotype}' WHERE primaryidentifier = '{rnai_id}'"
                ))
                updated += 1
            except Exception as e:
                logger.error(f"Error updating phenotyperemark for {rnai_id}: {e}")

    return updated


def add_hgnc_symbols(connection, hgnc_file, dry_run=False):
    """Add human gene symbols from HGNC file to secondaryidentifier"""
    if not Path(hgnc_file).exists():
        logger.warning(f"HGNC file not found: {hgnc_file}")
        return 0

    symbols = {}
    for line in Path(hgnc_file).read_text().splitlines():
        parts = line.split("\t")
        if len(parts) >= 2:
            symbols[parts[0]] = parts[1]

    if not symbols:
        logger.warning("No HGNC symbols loaded")
        return 0

    logger.info(f"Loaded {len(symbols)} HGNC symbols")

    if dry_run:
        logger.info("[DRY-RUN] Would update HGNC gene symbols")
        return 0

    updated = 0
    result = connection.execute(text("SELECT primaryidentifier FROM gene WHERE primaryidentifier LIKE '%HGNC%'"))
    for row in result:
        gene_id = row[0]
        if gene_id in symbols:
            try:
                connection.execute(text(
                    f"UPDATE gene SET secondaryidentifier = '{symbols[gene_id]}' WHERE primaryidentifier = '{gene_id}'"
                ))
                updated += 1
            except Exception as e:
                logger.error(f"Error updating HGNC symbol for {gene_id}: {e}")

    return updated


def remove_records(connection, table, identifiers, dry_run=False, batch_size=100):
    """Remove records from table by primaryidentifier"""
    if not identifiers:
        return 0

    total = len(identifiers)
    deleted = 0

    if dry_run:
        logger.info(f"[DRY-RUN] Would delete {total} records from {table}")
        return total

    # Batch delete for efficiency
    for i in range(0, total, batch_size):
        batch = identifiers[i:i + batch_size]
        placeholders = ", ".join([f"'{id}'" for id in batch])
        query = f"DELETE FROM {table} WHERE primaryidentifier IN ({placeholders})"

        try:
            result = connection.execute(text(query))
            deleted += result.rowcount
            logger.debug(f"Deleted batch {i//batch_size + 1}: {result.rowcount} rows")
        except Exception as e:
            logger.error(f"Error deleting from {table}: {e}")
            # Fall back to one-by-one for this batch
            for id in batch:
                try:
                    result = connection.execute(
                        text(f"DELETE FROM {table} WHERE primaryidentifier = '{id}'")
                    )
                    deleted += result.rowcount
                except Exception as e2:
                    logger.error(f"Failed to delete {id}: {e2}")

    return deleted


def process_removal_list(connection, model, input_dir, dry_run=False):
    """Process a single removal list file"""
    table = MODELS.get(model)
    if not table:
        logger.warning(f"Unknown model: {model}")
        return 0

    input_file = input_dir / f"to_remove_{model}.txt"
    if not input_file.exists():
        logger.debug(f"No removal list for {model}")
        return 0

    identifiers = [line.strip() for line in input_file.read_text().strip().split('\n') if line.strip()]

    if not identifiers:
        logger.debug(f"Empty removal list for {model}")
        return 0

    # Anatomy terms: clean CDATA, don't delete
    if model == 'anatomyterm':
        logger.info(f"Processing {model}: {len(identifiers)} records to clean CDATA")
        updated = clean_anatomy_cdata(connection, identifiers, dry_run)
        logger.info(f"Cleaned CDATA from {updated} records in {table}")
        return updated

    logger.info(f"Processing {model}: {len(identifiers)} records to remove")
    deleted = remove_records(connection, table, identifiers, dry_run)
    logger.info(f"Deleted {deleted} records from {table}")

    return deleted


def run_post_processing(database, input_dir, host='localhost', creds_file=None, dry_run=False, models=None, backup=False, backup_dir='./backups', clean_rnai=False, hgnc_file=None):
    """Run post-processing for all models"""
    connection, creds = get_connection(database, host, creds_file)
    input_dir = Path(input_dir)

    # Backup before making changes
    if backup and not dry_run:
        backup_database(database, host, creds, backup_dir)

    if dry_run:
        logger.warning("DRY-RUN MODE - no changes will be made")

    total_processed = 0

    # Clean RNAi CDATA if requested
    if clean_rnai:
        logger.info("Cleaning CDATA from RNAi records...")
        updated = clean_rnai_cdata(connection, dry_run)
        logger.info(f"Cleaned {updated} RNAi fields")
        total_processed += updated

    # Add HGNC symbols if file provided
    if hgnc_file:
        logger.info("Adding HGNC symbols...")
        updated = add_hgnc_symbols(connection, hgnc_file, dry_run)
        logger.info(f"Updated {updated} HGNC gene symbols")
        total_processed += updated

    # Process removal lists
    if input_dir.exists():
        removal_files = list(input_dir.glob("to_remove_*.txt"))
        if removal_files:
            logger.info(f"Found {len(removal_files)} removal list files")

            # Process in order: gene last (has most dependencies)
            process_order = ['anatomyterm', 'exon', 'mrna', 'cds', 'transcript', 'protein', 'allele', 'gene', 'organism']

            for model in process_order:
                if models and model not in models:
                    continue
                try:
                    processed = process_removal_list(connection, model, input_dir, dry_run)
                    total_processed += processed
                except Exception as e:
                    logger.error(f"Error processing {model}: {e}")
        else:
            logger.info("No removal list files found")
    else:
        logger.debug(f"Input directory not found: {input_dir}")

    logger.info("=" * 60)
    logger.info(f"Total records processed: {total_processed}")

    connection.close()


def main():
    parser = argparse.ArgumentParser(
        description='Post-process WormMine database using removal lists',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )

    parser.add_argument(
        'database',
        help='Database name (e.g., wormmine_final)'
    )

    parser.add_argument(
        '--input-dir', '-i',
        default='./removal_lists',
        help='Directory containing to_remove_*.txt files (default: ./removal_lists)'
    )

    parser.add_argument(
        '--host', '-H',
        default=DEFAULT_HOST,
        help=f'Database host (default: {DEFAULT_HOST})'
    )

    parser.add_argument(
        '--creds', '-c',
        help='Path to credentials file (user:password)'
    )

    parser.add_argument(
        '--dry-run', '-n',
        action='store_true',
        help='Show what would be deleted without making changes'
    )

    parser.add_argument(
        '--model', '-m',
        action='append',
        choices=list(MODELS.keys()),
        help='Process only specific model(s)'
    )

    parser.add_argument(
        '--backup', '-b',
        action='store_true',
        help='Backup database before processing (pg_dump)'
    )

    parser.add_argument(
        '--backup-dir',
        default='./backups',
        help='Directory for backups (default: ./backups)'
    )

    parser.add_argument(
        '--verbose', '-v',
        action='store_true',
        help='Enable verbose logging'
    )

    parser.add_argument(
        '--clean-rnai',
        action='store_true',
        help='Clean CDATA from RNAi remark, secondaryidentifier, phenotyperemark fields'
    )

    parser.add_argument(
        '--hgnc-file',
        help='Path to HGNC.txt file for adding human gene symbols'
    )

    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    run_post_processing(
        args.database,
        args.input_dir,
        args.host,
        args.creds,
        args.dry_run,
        args.model,
        args.backup,
        args.backup_dir,
        args.clean_rnai,
        args.hgnc_file
    )


if __name__ == '__main__':
    main()
